apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: sentiment-analysis
spec:
  vertices:
    - name: in
      source:
        http:
          service: true
    - name: sentiment-inference
      scale:
        min: 1
      udf:
        container:
          image: quay.io/whynowy/numaflow-demo/sentiment-analysis:v0.0.1
          imagePullPolicy: IfNotPresent
    - name: log
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: sentiment-inference
    - from: sentiment-inference
      to: log
