apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  # Reduce use case, group by key, with fixed window.
  name: even-odd-counter
spec:
  vertices:
    # Pipeline input, expects to receive integer numbers.
    - name: in
      scale:
        min: 1
      source:
        http:
          service: true
    # Map vertex, keying, give each number a key, even or odd
    - name: atoi
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-even-odd:v0.5.0
    # Reduce vertex, count the numbers of each key (even and odd)
    - name: count
      partitions: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/reduce-counter:v0.5.0
        groupBy:
          window:
            fixed:
              length: 10s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 90Mi
              accessMode: ReadWriteOnce
    # A log sink to display the results
    - name: log
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: atoi
    - from: atoi
      to: count
    - from: count
      to: log
