apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  # Reduce use case, group by key, with fixed window.
  name: even-odd-sum
spec:
  vertices:
    # Pipeline input, expects to receive integer numbers.
    - name: in
      source:
        http:
          service: true
    # Map vertex, keying, give each number a key, even or odd
    - name: atoi
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-even-odd:v0.5.0
    # Reduce vertex, compute the sum of the numbers of each key (even and odd)
    - name: compute-sum
      udf:
        container:
          image: quay.io/numaio/numaflow-go/reduce-sum:v0.5.0
        groupBy:
          window:
            fixed:
              # Every 5 seconds
              length: 5s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 50Mi
              accessMode: ReadWriteOnce
      partitions: 2
    # A log sink to display the results
    - name: sink
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: atoi
    - from: atoi
      to: compute-sum
    - from: compute-sum
      to: sink
